### ISSUE TITLE
Why can we insert items with same name?

### ISSUE THREAD

**Issue by jeffmgomes** [jeffmgomes/StartFinance#4]
I was able to add items with the same name. 

Was this behavior expected?

![ShoppingList - Same name](https://user-images.githubusercontent.com/37165659/54900406-05b97280-4f23-11e9-91ec-592c30050f4e.jpg)

![ShoppingList - Same items](https://user-images.githubusercontent.com/37165659/54900539-97c17b00-4f23-11e9-8608-cf27ac48f103.jpg)

**Comment by lysna87** [comment]
The SQL exception is never triggered because the IDs are unique. 
It would be nice to have the feature that prevents the same item from the same shop being added multiple times ,but that would involve an extra search query via the database, then somehow get the program to verify returned results, then act accordingly. I will not have time to do that and all of the troubleshooting that will go with it.
The user will have to delete extra records manually.
